  common: 
    containerRegistryURL: akscon101.azurecr.io
    ingressClass: azure-application-gateway
  ui: 
    replicas: 4
    image: 
      name: todo-ui
      tag: v1
    port: 80
    ServicePort: 80
    ingress:
      host: dev-todo-ui.jhandu.shop

  gettask: 
    replicas: 3
    image: 
      name: todo-get-task-api
      tag: v1
    port: 8000
    ServicePort: 80
    connectionString: Driver={ODBC Driver 18 for SQL Server};Server=tcp:neptual-sql-server.database.windows.net,1433;Database=my-sql-db;Uid=sqladminuser;Pwd=SqlAdmin@123;Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;
    ingress:
      host: dev-todo-get-task-api.jhandu.shop
      ingressClass: azure-application-gateway

  addtask: 
    replicas: 2
    image: 
      name: todo-add-tasks-api
      tag: v1
    port: 8000
    ServicePort: 80
    connectionString: Driver={ODBC Driver 18 for SQL Server};Server=tcp:neptual-sql-server.database.windows.net,1433;Database=my-sql-db;Uid=sqladminuser;Pwd=SqlAdmin@123;Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;
    ingress:
      host: dev-todo-add-tasks-api.jhandu.shop
      ingressClass: azure-application-gateway

  deletetask: 
    replicas: 3
    image: 
      name: todo-delete-tasks-api
      tag: v1
    port: 8000
    ServicePort: 80
    connectionString: Driver={ODBC Driver 18 for SQL Server};Server=tcp:neptual-sql-server.database.windows.net,1433;Database=my-sql-db;Uid=sqladminuser;Pwd=SqlAdmin@123;Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;
    ingress:
      host: dev-todo-delete-tasks-api.jhandu.shop
      ingressClass: azure-application-gateway