apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  namespace: argocd
spec:
  ingressClassName: {{ .Values.common.ingressClass}}
  rules:
    - host: {{ .Values.deletetask.ingress.host }}
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: {{ .Release.Name }}-todo-delete-tasks-api
                port:
                  number: {{ .Values.deletetask.port }}
